INSERT INTO PERSON(name, registered) VALUES ('Sherman', CURRENT_TIMESTAMP);
INSERT INTO PERSON(name, registered) VALUES ('Amabel', CURRENT_TIMESTAMP);
INSERT INTO PERSON(name, registered) VALUES ('Charlie', CURRENT_TIMESTAMP);

--
INSERT INTO SLOT(timeslot) VALUES('09:00:00');
INSERT INTO SLOT(timeslot) VALUES('09:30:00');
INSERT INTO SLOT(timeslot) VALUES('10:00:00');
INSERT INTO SLOT(timeslot) VALUES('10:30:00');
INSERT INTO SLOT(timeslot) VALUES('11:00:00');
INSERT INTO SLOT(timeslot) VALUES('11:30:00');
INSERT INTO SLOT(timeslot) VALUES('14:00:00');
INSERT INTO SLOT(timeslot) VALUES('14:30:00');
INSERT INTO SLOT(timeslot) VALUES('15:00:00');

--

INSERT INTO NURSE (name) values ('Lucy');
INSERT INTO NURSE (name) values ('Mark');
INSERT INTO NURSE (name) values ('Jane');

--