Select * from person;
--INSERT INTO PERSON(name, registered) VALUES ('Sherman', CURRENT_TIMESTAMP);
--INSERT INTO PERSON(name, registered) VALUES ('Amabel', CURRENT_TIMESTAMP);
--INSERT INTO PERSON(name, registered) VALUES ('Travis', CURRENT_TIMESTAMP);

--
--INSERT INTO SLOT(timeslot) VALUES('09:00:00');
--INSERT INTO SLOT(timeslot) VALUES('09:30:00');
--INSERT INTO SLOT(timeslot) VALUES('10:00:00');
--INSERT INTO SLOT(timeslot) VALUES('10:30:00');
--INSERT INTO SLOT(timeslot) VALUES('11:00:00');
--INSERT INTO SLOT(timeslot) VALUES('11:30:00');
--INSERT INTO SLOT(timeslot) VALUES('14:00:00');
--INSERT INTO SLOT(timeslot) VALUES('14:30:00');
--INSERT INTO SLOT(timeslot) VALUES('15:00:00');
--
----
--
--INSERT INTO NURSE (name) values ('Lucy');
--INSERT INTO NURSE (name) values ('Mark');
--INSERT INTO NURSE (name) values ('Jane');
--
----
--
--INSERT INTO VACCINATION_CENTRE (name, max_capacity) values ('Simei', '11');
--INSERT INTO VACCINATION_CENTRE (name, max_capacity) values ('City Hall', '10');
--INSERT INTO VACCINATION_CENTRE (name, max_capacity) values ('Kallang', '12');
--
----
--
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lucy', 2, 'Kallang');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Mark', 4, 'Kallang');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Jane', 4, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 1, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 2, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 3, 'Simeiang');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 5, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lopez', 6, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 7, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 8, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Irwin', 9, 'Simei');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 1, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 2, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 3, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 4, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 5, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lopez', 6, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 7, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 8, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Irwin', 9, 'City Hall');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 1, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 2, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 3, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 4, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 5, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lopez', 6, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 7, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 8, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Irwin', 9, 'Jurong West');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 1, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 2, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 3, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 4, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 5, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lopez', 6, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 7, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 8, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Irwin', 9, 'Woodlands');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 1, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 2, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 3, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Ghosh', 4, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 5, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Lopez', 6, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 7, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Xiang', 8, 'Bartley');
--INSERT into  NURSE_VACCINATION_CENTRE_TIMESLOT (nurse_name, slot_id, VACCINATION_CENTRE_name) values ('Irwin', 9, 'Bartley');
